name: 'Build Static Data Query'
description: 'GitHub Action for building and processing static data queries'
author: 'Stanislav'

inputs:
  game:
    description: 'The slug of the current game'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'

