name: 'static-data-upload-pipeline'
description: 'Merge new static data, validating and upload to the bucket'
author: 'Evgeniy'
inputs:
  token:
    required: true
    default: ${{ github.token }}

runs:
  using: 'node16'
  main:  'dist/index.js'
  env:
    GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
    GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}  