name: 'static-data-upload-pipeline'
description: 'Merge new static data, validating and upload to the bucket'
author: 'Evgeniy'
inputs:
  token:
    required: true
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/index.js'